FROM python:3.12


RUN mkdir /Backend
WORKDIR /Backend


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1  



RUN pip3 install fastapi uvicorn
RUN pip3 install pyodbc
RUN pip3 install --upgrade pip  


COPY . /Backend
RUN pip3 install -r requirements.txt
RUN ls -l




EXPOSE 2024


CMD uvicorn index:app --host 127.0.0.1 --port 2024