# Use a specific Python version
FROM python:3.12-slim AS build

WORKDIR /Backend

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install dependencies
RUN pip3 install fastapi uvicorn

RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the application code
COPY . .

# Runtime image
FROM python:3.12-slim

WORKDIR /Backend

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Copy only necessary files from the build stage
COPY --from=build /Backend /Backend

# Set the full path for uvicorn
ENV PATH="/Backend/.local/bin:${PATH}"

# Expose the port
EXPOSE 2024

# Command to run the application
CMD ["/Backend/.local/bin/uvicorn", "index:app", "--host", "127.0.0.1", "--port", "2024"]

