FROM python:3.12

RUN mkdir /Backend
WORKDIR /Backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1  

RUN pip3 install fastapi uvicorn
RUN pip3 install --upgrade pip  

COPY . /Backend



RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get -y install msodbcsql18 
RUN ACCEPT_EULA=Y apt-get -y install mssql-tools18 
run echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
run source ~/.bashrc
RUN apt-get -y install unixodbc-dev
sudo apt-get install -y libgssapi-krb5-2

RUN pip install pyodbc


COPY openssl.cnf /etc/ssl/openssl.cnf


RUN pip3 install -r requirements.txt


RUN apt update
RUN ls -l



EXPOSE 2024

CMD uvicorn index:app --host 0.0.0.0 --port 2024