from pydantic import BaseModel,Field, StrictInt



class trnSalesItem(BaseModel):
    SalesItemID:StrictInt|None=Field(default=0,format='int64')
    SalesID:StrictInt|None=Field(default=0,format='int64')
    OrderID:StrictInt|None=Field(default=0,format='int64')
    OrderItemID:StrictInt|None=Field(default=0,format='int64')
    ReturnSalesID:StrictInt|None=Field(default=0,format='int64')
    ReturnSalesItemID:StrictInt|None=Field(default=0,format='int64')
    ChallanID:StrictInt|None=Field(default=0,format='int64')
    ChallanItemID:StrictInt|None=Field(default=0,format='int64')
    ApprovalID:StrictInt|None=Field(default=0,format='int64')
    ApprovalItemID:StrictInt|None=Field(default=0,format='int64')
    SalesOrderID:StrictInt|None=Field(default=0,format='int64')
    SalesOrderItemID:StrictInt|None=Field(default=0,format='int64')
    BarcodeCancelID:StrictInt|None=Field(default=0,format='int64')
    BarcodeCancelItemID:StrictInt|None=Field(default=0,format='int64')
    RepairingID:StrictInt|None=Field(default=0,format='int64')
    RepairingItemID:StrictInt|None=Field(default=0,format='int64')
    ItemID:int | None= Field(default=0)
    ColorID:int | None= Field(default=0)
    SalesmanID:int | None= Field(default=0)
    HelperID:int | None= Field(default=0)
    TaxID:int | None= Field(default=0)
    AddBy:int | None= Field(default=0)
    SubCategory1ID:int | None= Field(default=0)
    SubCategory2ID:int | None= Field(default=0)
    SubCategory3ID:int | None= Field(default=0)
    PromoID:int | None= Field(default=0)
    BrandCategoryDiscID:int | None= Field(default=0)
    WebStockID:int | None= Field(default=0)
    AltrationID:int | None= Field(default=0)
    DeliveryTypeID:int | None= Field(default=0)
    PriceListItemID:int | None= Field(default=0)
    SalesmanCommCategoryID:int | None= Field(default=0)
    AlphaWebOrderItemID:int | None= Field(default=0)
    StockBrandID:int | None= Field(default=0)
    BranchID:int | None= Field(default=0)
    SubCategory4ID:int | None= Field(default=0)
    SubCategory5ID:int | None= Field(default=0)
    SubCategory6ID:int | None= Field(default=0)
    SubCategory7ID:int | None= Field(default=0)
    SubCategory8ID:int | None= Field(default=0)
    SubCategory9ID:int | None= Field(default=0)
    SubCategory10ID:int | None= Field(default=0)
    Qty:float | None= Field(default=0)
    FreeQty:float | None= Field(default=0)
    SalesRate:float | None= Field(default=0)
    MRP:float | None= Field(default=0)
    Amount:float | None= Field(default=0)
    DiscPrc:float | None= Field(default=0)
    DiscAmt:float | None= Field(default=0)
    ItemAmt:float | None= Field(default=0)
    AddLessPerItemAmt:float | None= Field(default=0)
    OtherAmt:float | None= Field(default=0)
    NetAmt:float | None= Field(default=0)
    TaxableAmt:float | None= Field(default=0)
    TaxPrc:float | None= Field(default=0)
    TaxAmt:float | None= Field(default=0)
    SurchargePrc:float | None= Field(default=0)
    SurchargeAmt:float | None= Field(default=0)
    AmtWithTax:float | None= Field(default=0)
    ActualRate:float | None= Field(default=0)
    MRPDiscPrc:float | None= Field(default=0)
    MRPDiscAmt:float | None= Field(default=0)
    SalesmanCommAmt:float | None= Field(default=0)
    SLMNCommBarcode:float | None= Field(default=0)
    SLMNCommAgeing:float | None= Field(default=0)
    SLMNCommPrc:float | None= Field(default=0)
    SLMNCommAmtwiseAmount:float | None= Field(default=0)
    RofAdjustAmt:float | None= Field(default=0)
    PurcRate:float | None= Field(default=0)
    ActualDiscPrc:float | None= Field(default=0)
    CGSTPrc:float | None= Field(default=0)
    CGSTAmt:float | None= Field(default=0)
    IGSTPrc:float | None= Field(default=0)
    IGSTAmt:float | None= Field(default=0)
    Pcs:float | None= Field(default=0)
    Meter:float | None= Field(default=0)
    OtherAddLessPerItem:float | None= Field(default=0)
    PerItemGiftVchAmt:float | None= Field(default=0)
    PurcCostRate:float | None= Field(default=0)
    HelperCommPrc:float | None= Field(default=0)
    HelperCommAmt:float | None= Field(default=0)
    HelperCommAmtWiseAmount:float | None= Field(default=0)
    ItemDeliveryAmt:float | None= Field(default=0)
    CessPrc:float | None= Field(default=0)
    CessAmt:float | None= Field(default=0)
    LoyaltyPerItemAmt:float | None= Field(default=0)
    HasMesurement:bool | None= Field(default=False)
    IsAlteration:bool | None= Field(default=False)
    IsItemBarcode:bool | None= Field(default=False)
    IsDeliveredWithoutSlip:bool | None= Field(default=False)
    SalesTypeSR:str | None= Field(default='')
    Barcode:str | None= Field(default='')
    LotNo:str | None= Field(default='')
    Size1:str | None= Field(default='')
    ReturnType:str | None= Field(default='')
    ReturnSalesVoucherNo:str | None= Field(default='')
    BarcodeTranType:str | None= Field(default='A')
    CompanyBarcode:str | None= Field(default='')
    DiscType:str | None= Field(default='')
    SalesTypeSR:str | None= Field(default='')