from pydantic import BaseModel,Field, StrictInt

class trnSalesitInput(BaseModel):
    SalesID:StrictInt|None=Field(default=0,format='int64')
    CreditNoteID:StrictInt|None=Field(default=0,format='int64')
    GiftCreditNoteID:StrictInt|None=Field(default=0,format='int64')
    CustomerTokenID:StrictInt|None=Field(default=0,format='int64')
    RepairingID:StrictInt|None=Field(default=0,format='int64')
    SalesType:str 
    CompanyID:int
    BranchID:int
    CompanyUnitID:int
    FinYearID:int
    DayBookID:int
    TranType:str
    VoucherNo:str| None= Field(default='')
    HomeDeliveryDate:str| None= Field(default='')
    VoucherDate:str| None= Field(default='')
    AccountID:int
    AccountName:str | None= Field(default='')
    MobileNo:str | None= Field(default='')
    Transport:str | None= Field(default='')
    LRNo:str | None= Field(default='')
    Destination:str | None= Field(default='')
    Remarks:str | None= Field(default='')
    PaymentMode:str | None= Field(default='')
    RateOn:str | None= Field(default='S')
    EntryFormType:str | None= Field(default='')
    InvoiceType:str | None= Field(default='')
    RefName:str | None= Field(default='')
    RefMobile1:str | None= Field(default='')
    CouponCode:str | None= Field(default='')
    BirthDayAnnvDiscTypeOn:str | None= Field(default='')
    AmazonOrderID:str | None= Field(default='')
    TCSApplicableType:str | None= Field(default='N')
    ReferenceNo:str | None= Field(default='')
    TCSDeductType:str | None= Field(default='A')
    TaxCalculationType:str | None= Field(default='')
    PaymentRequestID:str | None= Field(default='')
    LRDate:str | None= Field(default='')
    DeliveryDate:str | None= Field(default='')
    TrialDate:str | None= Field(default='')
    TaxableAmt:float | None= Field(default=0)
    NetAmt:float | None= Field(default=0)
    ReturnAmt:float | None= Field(default=0)
    DiscPrc:float | None= Field(default=0)
    DiscAmt:float | None= Field(default=0)
    MRP:float | None= Field(default=0)
    TaxableFreight:float | None= Field(default=0)
    TaxPrc:float | None= Field(default=0)
    TaxAmt:float | None= Field(default=0)
    SurchargePrc:float | None= Field(default=0)
    SurchargeAmt:float | None= Field(default=0)
    Freight:float | None= Field(default=0)
    ROFAmt:float | None= Field(default=0)
    TotalAmt:float | None= Field(default=0)
    TotalQty:float | None= Field(default=0)
    CashAmt:float | None= Field(default=0)
    CardAmt:float | None= Field(default=0)
    CardCommissionAmt:float | None= Field(default=0)
    ChequeAmt:float | None= Field(default=0)
    LoyaltyAmt:float | None= Field(default=0)
    CreditNoteUseAmt:float | None= Field(default=0)
    GiftVchUseAmt:float | None= Field(default=0)
    CreditNoteIssueAmt:float | None= Field(default=0)
    GiftVchIssueAmt:float | None= Field(default=0)
    CashNoteAmt:float | None= Field(default=0)
    CashNoteRefund:float | None= Field(default=0)
    AdjustmentAmt:float | None= Field(default=0)
    CashPaid:float | None= Field(default=0)
    OsAmt:float | None= Field(default=0)
    OtherLessAmt:float | None= Field(default=0)
    AdvanceAmt:float | None= Field(default=0)
    TotalCGSTAmt:float | None= Field(default=0)
    TotalIGSTAmt:float | None= Field(default=0)
    OrderAdvanceAmt:float | None= Field(default=0)
    ReceiptAdvanceAmt:float | None= Field(default=0)
    PrevSchemePoint:float | None= Field(default=0)
    PrevSchemeValue:float | None= Field(default=0)
    TCSTaxPrc:float | None= Field(default=0)
    TCSAppliOnAmt:float | None= Field(default=0)
    TCSTaxAmt:float | None= Field(default=0)
    TotalCessAmt:float | None= Field(default=0)
    TotalTenderAmt:float | None= Field(default=0)
    TaxID:int | None= Field(default=0)
    SalesmanID:int | None= Field(default=0)
    NoOfCartons:int | None= Field(default=0)
    CreditDays:int | None= Field(default=0)
    AddBy:int | None= Field(default=0)
    EditBy:int | None= Field(default=0)
    SchemeID:int | None= Field(default=0)
    CounterID:int | None= Field(default=0)
    RefID:int | None= Field(default=0)
    DeliveryBy:int | None= Field(default=0)
    CouponID:int | None= Field(default=0)
    AlphaWebOrderID:int | None= Field(default=0)
    ReferralID:int | None= Field(default=0)
    CompaignID:int | None= Field(default=0)
    SubCompaignID:int | None= Field(default=0)
    TotalAlterQty:int | None= Field(default=0)
    AddSeconds:int | None= Field(default=0)
    Form60Rec:bool | None= Field(default=False)
    IsHold:bool | None= Field(default=False)
    IsGenerateEwayBill:bool | None= Field(default=False)
    HomeDeliveryAvail:bool | None= Field(default=False)
    DoNotEntryLogHistory:bool | None= Field(default=False)
